# Generated by Django 5.1.6 on 2025-03-17 21:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bp_backend", "0002_painting_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="painting",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True
            ),
        ),
    ]
