# Generated by Django 5.1.7 on 2025-04-28 16:04

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_backend', '0002_add_caption_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
