# Generated by Django 5.1.6 on 2025-03-17 22:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bp_backend", "0003_painting_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painting",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
