# Generated by Django 5.1.7 on 2025-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_backend', '0004_alter_painting_caption_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='phash',
        ),
    ]
