# Generated by Django 5.1.7 on 2025-06-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_backend', '0005_remove_painting_phash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='subset',
        ),
    ]
