# Generated by Django 5.1.6 on 2025-03-18 20:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bp_backend", "0008_alter_painting_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="painting",
            name="detailed_caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="painting",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
